### PR TITLE
Updated the JS Bin ID for the ui-datepicker example - now points to a…

### PR DESCRIPTION
**Pull request by dannycallaghan**
...  fully working example.

Fixed issue discussed at  [New Example: ui datepicker](https://github.com/formly-js/angular-formly-website/issues/15)

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! Thanks! I noticed you took out the `wrapper: ['bootstrapLabel', 'bootstrapHasError'],` from the type definition. Was this intentional?

**Comment by kentcdodds** [comment]
If you add those back in, then you can take out the label stuff from the template (the `bootstrapLabel` will do it for you) and then you'll get the red glow when the field is invalid.

**Comment by dannycallaghan** [comment]
No, sorry, not intentional. Just an oversight when copying my code (which uses several wrappers) into the bin and making it generic.

Bin updated.

**Comment by kentcdodds** [comment]
Perfect. Thanks! It should be live in 3 minutes or so.

**Pull request merged**
