### PR TITLE
example: angular-material-lite

### PR DESCRIPTION
**Pull request by benoror**
example: material design lite (http://jsbin.com/bujuwi)

### CODE REVIEW

**Comment by kentcdodds** [comment]
Way cool! Looks like there are a few things that aren't bound to the model though, is that intentional?

**Comment by kentcdodds** [comment]
Specifically, I noticed gender and expensive weren't bound.

**Comment by benoror** [comment]
Oops sorry, corrected :smile:

**Comment by kentcdodds** [comment]
>  If you're interested in contributing to a full-on library, please comment here

Note, the angular-formly-templates-material is specifically supposed to integrate with the official angular-material library. We could create an angular-formly-templates-material-lite template library though. Do you want me to create a shell for that so you can link to that one instead?

**Comment by benoror** [comment]
That would be cool!. Although honestly I don't think I will be able to contribute significantly in the near term.

Maybe we can convince @jadjoubran ([angular-material-design-lite](https://github.com/jadjoubran/angular-material-design-lite) maintainer) to help, as it could potentially be a cool project to expose his library, launch it into the stratosphere thanks to angular-formly. ✌(◕‿-)✌

**Comment by kentcdodds** [comment]
:+1:

**Comment by jadjoubran** [comment]
thanks @benoror!
of course I'd be interested
How can we get started?

**Comment by benoror** [comment]
Cool! Maybe @kentcdodds can help us out making a shell repo first.

First you should learn more about this awesome library: https://github.com/formly-js/angular-formly#bookmark-links

Finally you might re-use some logic from this early implementation for angular-material: https://github.com/formly-js/angular-formly-templates-material

**Comment by kentcdodds** [comment]
@jadjoubran, I've created [a shell repo](https://github.com/formly-js/angular-formly-templates-material-lite) and added you as an admin on it. I recommend you look at [@benoror's example](http://angular-formly.com/#/example/integrations/angular-material-lite) (just published) and basically do the same thing only in a separate module. You can look at [the bootstrap templates](https://github.com/formly-js/angular-formly-templates-bootstrap) for an example.

**Comment by benoror** [comment]
Thanks @kentcdodds !

Also updated the jsbin's description link (https://github.com/formly-js/angular-formly-templates-material-lite/issues/1)

Kudos @jadjoubran !

**Comment by jadjoubran** [comment]
great thanks!
Is there any documentaiton on what the shell repo is? It's the first time I hear about formly but I get the idea.
And another quesiton, the shell is going to be on top of [angular-material-design-lite](https://github.com/jadjoubran/angular-material-design-lite)?

**Comment by kentcdodds** [comment]
So, basically, you own the repo: https://github.com/formly-js/angular-formly-templates-material-lite

You could take @benoror's example and create an angular module that does the same kind of thing (with the `formlyConfig` provider) and export that module as part of your library. You'll pretty much be doing the same thing as in: https://github.com/formly-js/angular-formly-templates-bootstrap

But how you build it is entirely up to you. You can use grunt/gulp/webpack whatever.

If you want a good starting point, I recommend you watch all the (free) egghead.io lessons here: http://learn.angular-formly.com

**Comment by jadjoubran** [comment]
that's great, thanks! I should probably push something by the weekend

**Comment by kentcdodds** [comment]
Awesome :-)

**Pull request merged**
