### PR TITLE
add input type example

### LINKED ISSUE #2: New Example: File Input in form
Hi, I would like to see an example of a file input type please.

### PR DESCRIPTION
**Pull request by sukrosono**
should close #2, and new issue for asked integration.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks

**Comment by sukrosono** [comment]
any time, we are partner right? :smile:

**Comment by kentcdodds** [comment]
:+1: In the future, please try to keep your pull request commit history clean. I prefer to not have merge commits in pull requests and generally prefer a single commit for one PR:
- [Rebase with master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github)
- [Squash multiple commits](https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits?series=how-to-contribute-to-an-open-source-project-on-github) (this one doesn't apply in this PR's case because you only had one commit)

Thanks again!

**Comment by sukrosono** [comment]
affirmative, sorry i just to happy then forgot to rebase it :smile: .
Thanks for your feedback

**Pull request merged**
