### PR TITLE
Color Picker

### PR DESCRIPTION
**Pull request by benoror**

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is awesome! A few things. You have this:

``` javascript
  // bindings
  angular.forEach([
  ], function(binding) {
    ngModelAttrs[camelize(binding)] = {bound: binding};
  });
```

Guessing that's leftover from cloning another jsbin.

Also, could you have a few more examples of using the other options? Like `color-picker-alpha`, `color-picker-format` etc.

**Comment by benoror** [comment]
Sure, let me improve it and i'll let you know

**Comment by benoror** [comment]
Fixed: http://jsbin.com/yogiye/9/

*ngModelAttrs use strings [as discussed here](https://gitter.im/formly-js/angular-formly?at=5575c130813c577e1cf5a617)

**Comment by kentcdodds** [comment]
Fantastic. Still would love to have multiple examples of using the different options available with that library :+1:

**Comment by benoror** [comment]
@kentcdodds Sure, take a look: http://jsbin.com/yogiye/10/

**Pull request merged**
