### PR TITLE
update: Add link for Angular 2 Formly

### PR DESCRIPTION
**Pull request by mohammedzamakhan**

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
@kentcdodds

**Comment by kentcdodds** [comment]
Thanks! I don't get notifications for this repo anymore.

**Comment by kentcdodds** [comment]
I'm sorry, but I'm having trouble building and deploying the website. You'll have to take it from here. You should have the permissions to do it. Just check out the package.json scripts. Hopefully you can get it working.

**Comment by mohammedzamakhan** [comment]
Got this error while pushing 

```
Warning: remote: Permission to formly-js/angular-formly-website.git denied to mohammedzamakhan.
fatal: unable to access 'https://github.com/formly-js/angular-formly-website.git/': The requested URL returned error: 403
 Use --force to continue.
```

**Comment by kentcdodds** [comment]
Permission granted :)

**Comment by mohammedzamakhan** [comment]
I am getting this error 
https://github.com/formly-js/angular-formly-website/issues/84

**Comment by kentcdodds** [comment]
Yeah, that was the error I was getting as well. Sorry :-/

**Pull request merged**
