### PR TITLE
Add GroupRaise to angular-formly users.

### PR DESCRIPTION
**Pull request by swifthand**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks awesome! Thanks!

**Comment by sukrosono** [comment]
@kentcdodds hi it should appear on http://angular-formly.com/#/users isn't it?
I don't see GroupRaise , just wondering. Because i chat on gitter like no one read it. I just see 7 user right now on the website.

**Comment by kamilkisiela** [comment]
@brutalcrozt The new version of website hasn't been deployed yet. You have to wait for @kentcdodds 

@kentcdodds I tried to deploy it but `bundle.js` had an error so I reverted my changes. Feel free reset it.

**Comment by kentcdodds** [comment]
Actually, the website makes an async request to this repo for the latest examples so it doesn't need to be redeployed for example changes. I'll look into this later.

**Comment by kentcdodds** [comment]
Whoops, was confused... This isn't an example change :-) let me look at it later. It should be deployed automatically by Tavis CI.

**Comment by kentcdodds** [comment]
Oh snap. Just kidding. It's been a while since I last looked at this. It's actually not automatic. I'll pull this down soon and manually deploy it. Sorry for the delay!

**Comment by kentcdodds** [comment]
So yeah, I'm getting this issue as well. It's been so long since we had to update the website that I think some of our transitive dependencies have broken us or something (should have shrinkwrapped).

Here's the issue to track this: https://github.com/formly-js/angular-formly-website/issues/84

I'm afraid I've used all my time up on this issue for the day. Sorry about that. Anyone can feel free to submit a PR that fixes this.

**Comment by kamilkisiela** [comment]
@kentcdodds I'm going to work on it in few minutes.

**Comment by sukrosono** [comment]
@kentcdodds @kamilkisiela i made some changes and it make build pass on my windows,
but i still wonder what `start` do? it keep say webpack bunlde is now VALID, but more than 4 min it's not return to promp. I just wait that before make PR

**Comment by kamilkisiela** [comment]
@brutalcrozt Feel free to submit a PR. I will test it.

`npm start` is to run webpack dev server. It runs website. Use this command and check `http://localhost:8080/webpack-dev-server/`

**Comment by kamilkisiela** [comment]
@brutalcrozt Submit a PR if it seems to work.

**Comment by kamilkisiela** [comment]
@kentcdodds @brutalcrozt 

Everything works now.

https://github.com/formly-js/angular-formly-website/compare/2abfce6...2fe3b0e

**Comment by sukrosono** [comment]
@kamilkisiela good job :+1: i can see GroupRaise now

**Comment by kentcdodds** [comment]
Thank you both for your help!

**Pull request merged**
